[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="modules" type="kotlin.collections.MutableSet<com.kgit2.ksp.model.FlagMaskModel>" file="templates/flag-mask-file.ftl" --]
[#-- @ftlvariable name="module" type="com.kgit2.ksp.model.FlagMaskModel" file="templates/flag-mask.ftl" --]
[#-- @ftlvariable name="modules" type="kotlin.collections.MutableSet<com.kgit2.ksp.model.RawDeclareModel>" file="templates/raw-file.ftl" --]
[#-- @ftlvariable name="packageName" type="java.lang.String" file="templates/raw-file.ftl" --]
[#-- @ftlvariable name="module" type="com.kgit2.ksp.model.RawDeclareModel" file="templates/raw-declare.ftl" --]
