package com.floater.git.common.option

enum class GitRepositoryOpenFlag(val value: UInt) {
    GIT_REPOSITORY_OPEN_NO_SEARCH(libgit2.GIT_REPOSITORY_OPEN_NO_SEARCH),
    GIT_REPOSITORY_OPEN_CROSS_FS(libgit2.GIT_REPOSITORY_OPEN_CROSS_FS),
    GIT_REPOSITORY_OPEN_BARE(libgit2.GIT_REPOSITORY_OPEN_BARE),
    GIT_REPOSITORY_OPEN_NO_DOTGIT(libgit2.GIT_REPOSITORY_OPEN_NO_DOTGIT),
    GIT_REPOSITORY_OPEN_FROM_ENV(libgit2.GIT_REPOSITORY_OPEN_FROM_ENV),
}

enum class GitRepositoryInitFlat(val value: UInt) {
    GIT_REPOSITORY_INIT_BARE(libgit2.GIT_REPOSITORY_INIT_BARE),
    GIT_REPOSITORY_INIT_NO_REINIT(libgit2.GIT_REPOSITORY_INIT_NO_REINIT),
    GIT_REPOSITORY_INIT_NO_DOTGIT_DIR(libgit2.GIT_REPOSITORY_INIT_NO_DOTGIT_DIR),
    GIT_REPOSITORY_INIT_MKDIR(libgit2.GIT_REPOSITORY_INIT_MKDIR),
    GIT_REPOSITORY_INIT_MKPATH(libgit2.GIT_REPOSITORY_INIT_MKPATH),
    GIT_REPOSITORY_INIT_EXTERNAL_TEMPLATE(libgit2.GIT_REPOSITORY_INIT_EXTERNAL_TEMPLATE),
    GIT_REPOSITORY_INIT_RELATIVE_GITLINK(libgit2.GIT_REPOSITORY_INIT_RELATIVE_GITLINK),
}

enum class RepositoryInitMode(val value: UInt) {
    GIT_REPOSITORY_INIT_SHARED_UMASK(libgit2.GIT_REPOSITORY_INIT_SHARED_UMASK),
    GIT_REPOSITORY_INIT_SHARED_GROUP(libgit2.GIT_REPOSITORY_INIT_SHARED_GROUP),
    GIT_REPOSITORY_INIT_SHARED_ALL(libgit2.GIT_REPOSITORY_INIT_SHARED_ALL),
}
